# Name            Beta   Restriction  SubsidiesDay  UCIThreshold
LaissezFaire      0.35   0.00         0.0           -1.0
Lockdown          0.05   0.60         1500000.0     -1.0
RemoteWork        0.15   0.15         300000.0      -1.0
DynamicSignals    0.35   0.50         1000000.0      0.80